#ifndef CS_ACHIEVEMENTDEFS_H
#define CS_ACHIEVEMENTDEFS_H
#ifdef _WIN32
#pragma once
#endif



#define ALL_WEARING_SAME_UNIFORM_ACHIEVEMENT 0

typedef enum
{
	CSInvalidAchievement = -1,

	CSBombAchievementsStart = 1000,           

	CSWinBombPlant,
	CSWinBombDefuse,
	CSDefuseAndNeededKit,
	CSBombDefuseCloseCall,
	CSKilledDefuser,
	CSPlantBombWithin25Seconds,
	CSKillBombPickup,
	CSBombMultikill,
	CSGooseChase,
	CSWinBombPlantAfterRecovery,
	CSDefuseDefense,
	CSPlantBombsLow,
	CSDefuseBombsLow,
	CSPlantBombsTRLow,
	CSDefuseBombsTRLow,

	CSBombAchievementsEnd,                        


	CSHostageAchievementsStart = 2000,         

	CSRescueAllHostagesInARound,
	CSKilledRescuer,
	CSFastHostageRescue,
	CSRescueHostagesLow,
	CSRescueHostagesMid,

	CSHostageAchievmentEnd,                       

	CSKillAchievementsStart = 3000,            

	CSEnemyKillsLow,
	CSEnemyKillsMed,
	CSEnemyKillsHigh,
	CSSurvivedHeadshotDueToHelmet,
	CSKillEnemyReloading,
	CSKillingSpree,
	CSKillsWithMultipleGuns,
	CSHeadshots,
	CSAvengeFriend,
	CSSurviveGrenade,
	CSDominationsLow,
	CSDominationsHigh,
	CSRevengesLow,
	CSRevengesHigh,
	CSDominationOverkillsLow,
	CSDominationOverkillsHigh,
	CSDominationOverkillsMatch,
	CSExtendedDomination,
	CSConcurrentDominations,
	CSKillEnemyBlinded,
	CSKillEnemiesWhileBlind,
	CSKillEnemiesWhileBlindHard,
	CSKillsEnemyWeapon,
	CSKillWithEveryWeapon,
	CSWinKnifeFightsLow,
	CSWinKnifeFightsHigh,
	CSKilledDefuserWithGrenade,
	CSKillSniperWithSniper,
	CSKillSniperWithKnife,
	CSHipShot,
	CSKillSnipers,
	CSKillWhenAtLowHealth,
	CSPistolRoundKnifeKill,
	CSWinDualDuel,
	CSGrenadeMultikill,
	CSKillWhileInAir,
	CSKillEnemyInAir,
	CSKillerAndEnemyInAir,
	CSKillEnemyWithFormerGun,
	CSKillTwoWithOneShot,
	CSProgressiveGameKills,
	CSSelectGameKills,
	CSBombGameKills,
	CSGunGameKillKnifer,
	CSGunGameKnifeSuicide,
	CSGunGameKnifeKillKnifer,
	CSGunGameSMGKillKnifer,
	CSFirstBulletKills,
	CSSpawnCamper,
	CSBornReady,

	CSKillAchievementEnd,                         

	CSWeaponAchievementsStart = 4000,          

	CSEnemyKillsDeagle,
	CSEnemyKillsUSP,
	CSEnemyKillsGlock,
	CSEnemyKillsP228,
	CSEnemyKillsElite,
	CSEnemyKillsFiveSeven,
	CSEnemyKillsBizon,
	CSEnemyKillsTec9,
	CSEnemyKillsTaser,
	CSEnemyKillsHKP2000,
	CSEnemyKillsP250,
	CSEnemyKillsAWP,
	CSEnemyKillsAK47,
	CSEnemyKillsM4A1,
	CSEnemyKillsAUG,
	CSEnemyKillsSG552,
	CSEnemyKillsSG550,
	CSEnemyKillsGALIL,
	CSEnemyKillsGALILAR,
	CSEnemyKillsFAMAS,
	CSEnemyKillsScout,
	CSEnemyKillsG3SG1,
	CSEnemyKillsSCAR17,
	CSEnemyKillsSCAR20,
	CSEnemyKillsSG556,
	CSEnemyKillsSSG08,
	CSEnemyKillsP90,
	CSEnemyKillsMP5NAVY,
	CSEnemyKillsTMP,
	CSEnemyKillsMAC10,
	CSEnemyKillsUMP45,
	CSEnemyKillsMP7,
	CSEnemyKillsMP9,
	CSEnemyKillsM3,
	CSEnemyKillsXM1014,
	CSEnemyKillsMag7,
	CSEnemyKillsSawedoff,
	CSEnemyKillsNova,
	CSEnemyKillsM249,
	CSEnemyKillsNegev,
	CSEnemyKillsKnife,
	CSEnemyKillsHEGrenade,
	CSEnemyKillsMolotov,
	CSMetaPistol,
	CSMetaRifle,
	CSMetaSMG,
	CSMetaShotgun,
	CSMetaWeaponMaster,

	CSWeaponAchievementsEnd,                      

	CSGeneralAchievementsStart = 5000,         

	CSWinRoundsLow,
	CSWinRoundsMed,
	CSWinRoundsHigh,
	CSGGWinRoundsLow,
	CSGGWinRoundsMed,
	CSGGWinRoundsHigh,
	CSGGWinRoundsExtreme,
	CSGGWinRoundsUltimate,
	CSGGRoundsLow,
	CSGGRoundsMed,
	CSGGRoundsHigh,
	CSMoneyEarnedLow,
	CSMoneyEarnedMed,
	CSMoneyEarnedHigh,
	CSGiveDamageLow,
	CSGiveDamageMed,
	CSGiveDamageHigh,
	CSPosthumousGrenadeKill,
	CSKillEnemyTeam,
	CSLastPlayerAlive,
	CSKillEnemyLastBullet,
	CSKillingSpreeEnder,
	CSDamageNoKill,
	CSKillLowDamage,
	CSSurviveManyAttacks,
	CSLosslessExtermination,
	CSFlawlessVictory,
	CSDecalSprays,
	CSBreakWindows,
	CSBreakProps,
	CSUnstoppableForce,
	CSImmovableObject,
	CSHeadshotsInRound,
	CSWinPistolRoundsLow,
	CSWinPistolRoundsMed,
	CSWinPistolRoundsHigh,
	CSFastRoundWin,
	CSNightvisionDamage,
	CSSilentWin,
	CSBloodlessVictory,
	CSDonateWeapons,
	CSWinRoundsWithoutBuying,
#if(ALL_WEARING_SAME_UNIFORM_ACHIEVEMENT)
	CSSameUniform,
#endif
	CSFriendsSameUniform,
	CSCauseFriendlyFireWithFlashbang,

	CSGeneralAchievementsEnd,                     

	CSWinMapAchievementsStart = 6000,

	CSWinMapCS_ASSAULT,
	CSWinMapCS_COMPOUND,
	CSWinMapCS_HAVANA,
	CSWinMapCS_ITALY,
	CSWinMapCS_MILITIA,
	CSWinMapCS_OFFICE,
	CSWinMapDE_AZTEC,
	CSWinMapDE_CBBLE,
	CSWinMapDE_CHATEAU,
	CSWinMapDE_DUST,
	CSWinMapDE_DUST2,
	CSWinMapDE_INFERNO,
	CSWinMapDE_NUKE,
	CSWinMapDE_PIRANESI,
	CSWinMapDE_PORT,
	CSWinMapDE_PRODIGY,
	CSWinMapDE_TIDES,
	CSWinMapDE_TRAIN,

	CSWinMatchDE_SHORTTRAIN,
	CSWinMatchDE_LAKE,
	CSWinMatchDE_SAFEHOUSE,
	CSWinMatchDE_SUGARCANE,
	CSWinMatchDE_STMARC,
	CSWinMatchDE_BANK,
	CSWinMatchDE_EMBASSY,
	CSWinMatchDE_DEPOT,
	CSWinMatchDE_VERTIGO,
	CSWinMatchDE_BALKAN,
	CSWinMatchAR_MONASTERY,
	CSWinMatchAR_SHOOTS,
	CSWinMatchAR_BAGGAGE,
	CSWinEveryGGMap,
	CSPlayEveryGGMap,
	CSGunGameProgressiveRampage,
	CSGunGameFirstKill,
	CSKillEnemyTerrTeamBeforeBombPlant,
	CSKillEnemyCTTeamBeforeBombPlant,
	CSGunGameConservationist,
	CSStillAlive,
	CSMedalist,

	CSWinMapAchievementsEnd,                      

	CSSeason1_Start = 6200,
	CSSeason1_Bronze,
	CSSeason1_Silver,
	CSSeason1_Gold,
	CSSeason1_End                      

} eCSAchievementType;


#endif  